var translations =
{
  "dashboard": "Dashboard",
  "dich_vu": "Dịch vụ",
  "goi_cuoc": "Gói cước",
  "khuyen_mai": "Khuyến mại",
  "tin_tuc": "Tin tức",
  "ung_dung": "Ứng dụng",
  "hot_news": "Hot news",
  "kh_than_thiet": "Khách hàng thân thiết",
  "trai_nghiem_3g_4g": "Trải nghiệm 3G/4G",
  "logs": "Logs",
  "users": "Users",
  "thong_ke_app": "Thống kê app",
  "banner_quang_cao": "Banner quảng cáo",
  "khac": "Khác",
  "them_moi_dich_vu": "Thêm mới dịch vụ",
  "ma_dich_vu": "Mã dịch vụ",
  "ten_dich_vu": "Tên dịch vụ",
  "nhom_dich_vu": "Nhóm dịch vụ",
  "mo_ta_ngan": "Mô tả ngắn",
  "mo_ta_chi_tiet": "Mô tả chi tiết",
  "anh_mo_ta": "Ảnh mô tả",
  "link_web": "Link web",
  "chon_anh": "Tải lên",
  "doi_anh": "Đổi",
  "xoa_anh": "Xóa",
  "xoa": "Xóa",
  "lam_moi": "Làm mới",
  "tieu_de": "Tiêu đề",
  "nguon": "Nguồn",
  "ngay_phat_hanh": "Ngày phát hành",
  "chuc_nang": "Chức năng",
  "them_moi": "Thêm mới",
  "huy": "Hủy",
  "them_moi_tin_tuc": "Thêm mới tin tức",
  "icon": "Icon",
  "ma_goi_cuoc": "Mã gói cước",
  "ten_goi_cuoc": "Tên gói cước",
  "them_moi_goi_cuoc": "Thêm mới gói cước",
  "ngon_ngu": "Ngôn ngữ",
  "tieng_viet": "Tiếng Việt",
  "tieng_anh": "Tiếng Anh",
  "tieng_lao": "Lao",
  "them": "Thêm",
  "them_moi_goi_cuoc": "Thêm mới gói cước",
  "luu": "Lưu",
  "loai_goi_cuoc": "Loại gói cước",
  "dung_luong": "Dung lượng (MB)",
  "gia": "Giá",
  "don_vi": "Đơn vị",
  "sua_goi_cuoc": "Sửa gói cước",
  "them_moi_khuyen_mai": "Thêm mới khuyến mại",
  "tieu_de": "Tiêu đề",
  "ngay_hieu_luc": "Ngày hiệu lực",
  "ngay_het_hieu_luc": "Ngày hết hiệu lực",
  "cua_hang_diem_ban": "Cửa hàng/Điểm bán",
  "kieu_tin": "Kiểu tin",
  "tin_khuyen_mai": "Tin khuyến mại",
  "ma_khuyen_mai": "Mã khuyến mại",
  "ten_ung_dung": "Tên ứng dụng",
  "lien_ket_den_app_store": "Liên kết đến App Store",
  "lien_ket_den_google_play": "Liên kết đến Google Play",
  "loai_tin": "Loại tin",
  "thu_tu_uu_tien": "Thứ tự ưu tiên",
  "trang_thai": "Trạng thái",
  "trang_thai_hien_thi": "Hiển thị",
  "trang_thai_an": "Ẩn",
  "kieu": "Kiểu",
  "ten": "Tên",
  "link_chi_tiet": "Link chi tiết",
  "them_banner_moi": "Thêm banner mới",
  "them_diem_ban_cua_hang_moi": "Thêm điểm bán/cửa hàng mới",
  "dia_chi": "Địa chỉ",
  "so_dien_thoai": "Số điện thoại",
  "quan_huyen": "Quận/Huyện",
  "tinh_thanh_pho": "Tỉnh/Thành phố",
  "gio_mo_cua": "Giờ mở cửa",
  "kinh_do": "Kinh độ",
  "vi_do": "Vĩ độ",
  "trang_hien_thi": "Trang hiển thị",
  "them_tin_moi": "Thêm tin mới",
  "them_moi_ung_dung": "Thêm mới ứng dụng",
  "chon_loai_tin": "Chọn loại tin",
  "them_moi_link_trai_nghiem": "Thêm mới link trải nghiệm",
  "language": "Ngôn ngữ",
  "cua_hang": "Cửa hàng",
  "diem_ban": "Điểm bán",
  "loai": "Loại",
  "cap_nhat_ung_dung": "Cập nhật ứng dụng",
  "cap_nhat_tin_moi": "Cập nhật tin mới",
  "cap_nhat_tin_tuc": "Cập nhật tin tức",
  "cap_nhat_link_trai_nghiem": "Cập nhật link trải nghiệm",
  "cap_nhat_diem_ban_cua_hang_moi": "Cập nhật điểm bán/ Cửa hàng mới",
  "tim_kiem": "Tìm kiếm",
  "thong_ke_thue_bao": "Thống kê thuê bao",
  "thong_ke_yeu_cau": "Thống kê yêu cầu",
  "phan_bo_theo_nen_tang_hdh": "Phân bố theo nền tảng HĐH",
  "tong_so_thue_bao": "Tổng số thuê bao",
  "thue_bao_moi_dang_ky": "Thuê bao mới đăng ký",
  "thue_bao_hoat_dong": "Thuê bao hoạt động",
  "loi_giao_dich_chua_xu_ly": "Lỗi giao dịch chưa xử lý",
  "trieu": "triệu",
  "nghin": "nghìn",
  "active_users": "Active users",
  "dau_so": "Đầu số",
  "chon_hoat_dong": "Chọn hoạt động",
  "la_goi_data": "Là gói data",
  "goi_data": "Gói data",
  "kieu_dich_vu": "Kiểu dịch vụ",
  "ten_web_service": "Tên web service",
  "tham_so": "Tham số",
  "ten_dang_nhap": "Tên đăng nhập",
  "mat_khau": "Mật khẩu",
  "mo_ta": "Mô tả",
  "them_web_service": "Thêm webservice",
  "cap_nhat_web_service": "Cập nhật webservice",
  "dang_xuat": "Đăng xuất",
  "cap_nhat_dich_vu": "Cập nhật dịch vụ",
  "danh_sach_job": "Danh sách công việc",
  "danh_sach_so_thich": "Danh sách sở thích",
  "cap_nhat_khuyen_mai": "Cập nhật khuyến mại",
  "web_service": "Web service",
  "noi_dung": "Nội dung",
  "tat_ca": "Tất cả",
  "trang_trai_nghiem_3g_4g": "Trang trải nghiệm 3g/4g",
  "trang_gioi_thieu_ung_dung": "Trang giới thiệu ứng dụng",
  "from_date": "Từ ngày",
  "to_date": "Đến ngày",
  "hien_thi": "Hiển thị",
  "hien": "Hiện",
  "an": "Ẩn",
  "chon_tinh_thanh_pho": "Chọn tỉnh/thành phố",
  "chon_quan_huyen": "Chọn quận/huyện",
  "chon_nhom_dich_vu": "Chọn nhóm dịch vụ",
  "chon_dich_vu": "Chọn dịch vụ",
  "lien_ket": "Liên kết",
  "danh_sach_goi_cuoc": "Danh sách gói cước",
  "hoat_dong": "Hoạt động",
  "dang_nhap_he_thong": "Đăng nhập vào hệ thống",
  "username": "Tên đăng nhập",
  "password": "Mật khẩu",
  "login": "Đăng nhập",
  "duong_dan_anh": "Đường dẫn ảnh",
  "registerable": "Registerable",
  "Un-Registerable":"Un-Registerable",
  "": "",
  //Notification
  "thong_bao": "Thông báo",
  "them_moi_notification": 'Add new notification',
  "cap_nhat_notification": 'Edit notification',
}


var validateMessages = {
  ErrRequired: "Bạn chưa nhập dữ liệu",
  ErrMaxLength2: "Không được quá 2 ký tự",
  ErrMaxLength20: "Không được quá 20 ký tự",
  ErrMaxLength10: "Không được quá 10 ký tự",
  ErrMaxLength5: "Không được quá 5 ký tự",
  ErrMaxLength6: "Không được quá 6 ký tự",
  ErrMaxLength50: "Không được quá 50 ký tự",
  ErrMaxLength100: "Không được quá 100 ký tự",
  ErrMaxLength200: "Không được quá 200 ký tự",
  ErrMaxLength1000: "Không được quá 1000 ký tự",
  ErrMaxLength2000: "Không được quá 2000 ký tự",
  ErrMaxLength4000: "Không được quá 4000 ký tự",
  ErrMaxLength: "Ký tự nhập vào quá dài",
  ErrRequiredLanguage: "Bạn chưa chọn ngôn ngữ",
  ErrRequiredGroupId: "Bạn chưa chọn nhóm dịch vụ",
  ErrUrl: "Url không hợp lệ",
  ErrDate: "Ngày không hợp lệ",
  ErrMin: "Số nhập vào phải lớn hơn -999",
  ErrMax: "Số nhập vào phải nhỏ hơn 999",
  ErrNumber: "Phải nhập số",
  ErrNotValidInput: "Đầu vào không hợp lệ",
  ErrMaxLengthSpecific: "số ký tự dài nhất là",
  ErrRequiredSpecific: "trường bắt buộc",
  ErrEffectTimeReq: "Bạn cần nhập ngày hiệu lực",
  ErrPublicTimeReq: "Bạn cần nhập ngày phát hành",
  ErrExpiredTimeReq: "Bạn cần nhập ngày hết hiệu lực",
  ErrPhonePattern: "Số điện thoại không chính xác",
  ErrIntNumber: "Số nhập vào phải là dạng số nguyên",
  ErrMinValue0: "Số nhập vào phải >= 0",
  expireDate_larger_effectDate: "Ngày hết hạn phải lớn hơn ngày hiệu lực",
  ErrImageLink: "Đường dẫn ảnh không hợp lệ",
  ErrMinSpecific: "Nhỏ nhất là",
  ErrMaxSpecific: "Lớn nhất là"
}

var notiMessages = {
  addSuccessMes: "Thêm thành công",
  putSuccessMes: "Cập nhật thành công",
  errMes: "Không thực hiện được",
  addServiceSuccessMes: "Thêm thành công gói cước",
  notFound: "Không tìm thấy",
  loginRequire: "Bạn hãy đăng nhập lại để sử dụng",
  ajaxWaiting: "<h2>Chờ mình chút...</h2>",
  errEffectiveTimeLagrerThanExpiredTime: "Ngày hiệu lực phải nhỏ hơn hoặc bằng ngày hết hiệu lực",
  loginFailed: "Tài khoản hoặc mật khẩu không đúng!"
}

var tableTitles = {
  order: "STT",
  serviceType: "Dịch vụ",
  promotionType: "Khuyến mãi",
  newsType: "Tin tức",
  action: "Hành động",
  deleteMessage: "Bạn muốn xóa dữ liệu này không?",
  successAddMessage: "Đã thêm thành công",
  successDeleteMessage: "Đã xóa thành công",
  successUpdateMessage: "Cập nhật thành công",
  errorMessage: "Lỗi!",
  errorLoad: "Không load được",
  edit: "Sửa",
  delete: "Xóa",
  cancel: "Hủy",
  submit: "Xác nhận",
  approvedMessage: "Bản ghi đã được duyệt",
  unApprovedMessage: "Bản ghi hủy duyệt",
  approveAll: "Approve all",
  error: "Lỗi",
  total: "Tổng số",
  record: "bản ghi",
  save: "Lưu",
  empty: "Không có bản ghi nào",
  search: "Tìm kiếm",
  infoFilter: "(Lọc từ tổng số",
  zeroRecords: "Không tìm thấy bản ghi phù hợp",
  addNew: "Thêm mới",
  refresh: "Làm mới",
  //service group
  groupCode: "Mã nhóm",
  groupName: "Tên nhóm",
  description: "Mô tả",
  language: "Ngôn ngữ ",
  createdTime: "Ngày tạo",
  //service
  serviceCode: "Mã dịch vụ",
  serviceName: "Tên dịch vụ",
  shortDescription: "Mô tả ngắn",
  serviceGroup: "Nhóm dịch vụ",
  icon: "Icon",
  webLink: "Link",

  //sub service
  subserviceCode: "Mã gói cước",
  subserviceName: "Tên gói cước",
  includedInService: "Thuộc dịch vụ",

  //actions
  id: "ID",
  actionName: "Tên hoạt động",
  actionType: "Loại hoạt động",
  channelType: "Loại kênh",
  syntax: "Cú pháp",
  channel: "Channel",
  webservice: "Webservice",
  register: "Đăng ký",

  //Webservice
  name: "Tên",
  url: "Url",
  parameter: "Tham số",
  xmlString: "Chuỗi XML",
  //Promotions
  title: "Tiêu đề",
  effectiveDate: "Ngày hiệu lực",
  expiredDate: "Ngày hết hạn",
  publishingTime: "Ngày phát hành",
  //news

	service: "Dịch vụ",
	promotion: "Khuyến mãi",
	news: "Tin tức",
  sourceLink: "Nguồn",
  imgDes: "Ảnh mô tả",
  //application
  applicationName: "Tên ứng dụng",
  type: "Kiểu",
  //hotnews
  image: "Ảnh",
  orderOfPrecedence: "Thứ tự ưu tiên",
  effectiveTime: "Hiệu lực",
  expiredTime: "Hết hiệu lực",
  display: "Hiển thị",
  isShow: "Hiện",
  notShow: "Ẩn",
  newsOfType: "Loại tin",
  yes: "Có",
  no: "Không",
  //store
  phoneNumber: "Số điện thoại",
  address: "Địa chỉ",
  openTime: "Giờ mở cửa",

  //experiment link
  linkName: "Tên liên kết",


  //banner
  bannerImage: "Ảnh banner",
  messageType: "Loại tin",
  serviceAd: "Dịch vụ",
  promotionAd: "Khuyến mãi",
  newsAd: "Tin tức",
  otherAd: "Khác",
  notWorking: "Không hoạt động",
  isWorking: "Đang hoạt động",
  all: "Tất cả",
  applicationPage: "Trang ứng dụng",
  experimentPage: "Trang trải nghiệm 3G/4G",
  status: "Trạng thái",

  //user
  fullName: "Tên đầy đủ",
  loginName: "Tên đăng nhập",
  password: "Mật khẩu",
  role: "Vai trò",
  admin: "Admin",
  contentManager: "Content Manager",

  fromDate: "Từ ngày",
  toDate: "Đến ngày",

  //other
  jobTitle: "Tên công việc",
  hobbyTitle: "Tên sở thích",
  longitude: "Kinh độ",
  latitude: "Vĩ độ",
  province: "Tỉnh/Thành phố",
  district: "Quận/Huyện",
  //search placeholder
  searchJob: "Tìm tên job",
  searchHobby: "Tìm tên sở thích",
  searchShop: "Tìm theo tên",
  searchBanner: "Tìm kiếm theo mô tả",
  searchExprLink: "Tìm kiếm theo tên",
  searchNews: "Tìm tiêu đề tin tức",
  searchApplication: "Tìm tên ứng dụng",
  searchPromotion: "Tìm theo tiêu đề",
  searchWebservice: "Tìm theo tên",
  searchSubservice: "Tìm kiếm gói cước",
  searchService: "Tìm tên dịch vụ",
  searchServiceGroup: "Tìm tên nhóm dịch vụ",
  searchHotnews: "Tìm kiếm tin mới",
  searchWebservice: "Tìm kiếm theo tên",
  //Notification
  message: "Thông báo",
  startTime: "Thời gian bắt đầu",
  endTime: "Thời gian kết thúc",

}
