var translations =
{
  "dashboard": "Dashboard",
  "dich_vu": "Service",
  "goi_cuoc": "Sub Service",
  "khuyen_mai": "Promotion",
  "tin_tuc": "News",
  "ung_dung": "Applications",
  "hot_news": "Hot news",
  "kh_than_thiet": "Loyal customers",
  "trai_nghiem_3g_4g": "3G/4G experience",
  "logs": "Logs",
  "users": "Users",
  "thong_ke_app": "Statistics app",
  "banner_quang_cao": "Advertising banner",
  "khac": "Others",
  "them_moi_dich_vu": "Add service",
  "ma_dich_vu": "Service code",
  "ten_dich_vu": "Servie name",
  "nhom_dich_vu": "Service group",
  "mo_ta_ngan": "Short descrtiption",
  "mo_ta_chi_tiet": "Description",
  "anh_mo_ta": "Image",
  "link_web": "Link web",
  "chon_anh": "Upload",
  "doi_anh": "Change",
  "xoa_anh": "Delete",
  "xoa": "Delete",
  "lam_moi": "Refresh",
  "tieu_de": "Title",
  "nguon": "Source URL",
  "ngay_phat_hanh": "Publish date",
  "chuc_nang": "Function",
  "them_moi": "Add",
  "huy": "Discard",
  "them_moi_tin_tuc": "Add news",
  "icon": "Icon",
  "ma_goi_cuoc": "Subservice code",
  "ten_goi_cuoc": "Subservice name",
  "them_moi_goi_cuoc": "Add subservice",
  "ngon_ngu": "Language",
  "tieng_viet": "Vietnamese",
  "tieng_anh": "English",
  "tieng_lao":"Lao",
  "them": "Add",
  "them_moi_goi_cuoc": "Add Subservice",
  "luu": "Save",
  "loai_goi_cuoc": "Subservice type",
  "dung_luong": "Volume (MB)",
  "gia": "Price",
  "don_vi": "Unit",
  "sua_goi_cuoc": "Edit subservice",
  "them_moi_khuyen_mai": "Add promotion",
  "ngay_hieu_luc": "Effect date",
  "ngay_het_hieu_luc": "Expire date",
  "cua_hang_diem_ban": "Shops",
  "kieu_tin": "News Type",
  "tin_khuyen_mai": "Promotion news",
  "ma_khuyen_mai": "Promotion code",
  "ten_ung_dung": "Application name",
  "lien_ket_den_app_store": "App Store link",
  "lien_ket_den_google_play": "Google Play link",
  "loai_tin": "News Type",
  "thu_tu_uu_tien": "Priority",
  "trang_thai": "Status",
  "trang_thai_hien_thi": "Show",
  "trang_thai_an": "Hide",
  "kieu": "Type",
  "ten": "Name",
  "link_chi_tiet": "Url detail",
  "them_banner_moi": "Add banner",
  "them_diem_ban_cua_hang_moi": "Add Shop",
  "dia_chi": "Address",
  "so_dien_thoai": "Phone number",
  "quan_huyen": "District",
  "tinh_thanh_pho": "Province",
  "gio_mo_cua": "Open hour",
  "kinh_do": "Longitude",
  "vi_do": "Latitude",
  "trang_hien_thi": "Page",
  "them_moi_link_trai_nghiem": "Add experience link",
  "them_tin_moi": "Add hot news",
  "them_moi_ung_dung": "Add application",
  "chon_loai_tin": "News type",
  "language": "Language",
  "trang_hien_thi": "Page",
  "cua_hang": "Shop",
  "diem_ban": "Point of Sale",
  "loai": "Type",
  "cap_nhat_ung_dung": "Update application",
  "cap_nhat_tin_moi": "Update hot news",
  "cap_nhat_tin_tuc": "Update news",
  "cap_nhat_link_trai_nghiem": "Update experience link",
  "cap_nhat_diem_ban_cua_hang_moi": "Update shop/point of sale",
  "tim_kiem": "Search",
  "thong_ke_thue_bao": "Subscriber",
  "thong_ke_yeu_cau": "Request",
  "phan_bo_theo_nen_tang_hdh": "Os type",
  "tong_so_thue_bao": "Total subscriber",
  "thue_bao_moi_dang_ky": "New subscriber",
  "thue_bao_hoat_dong": "Active subscriber",
  "loi_giao_dich_chua_xu_ly": "Transaction logs",
  "trieu": "triệu",
  "nghin": "nghìn",
  "active_users": "Active users",
  "dau_so": "Short code",
  "chon_hoat_dong": "Action",
  "la_goi_data": "Is data package",
  "goi_data": "Data package",
  "kieu_dich_vu": "Service type",
  "ten_web_service": "Web service name",
  "tham_so": "Params",
  "ten_dang_nhap": "User name",
  "mat_khau": "Password",
  "mo_ta": "Description",
  "them_web_service": "Add webservice",
  "cap_nhat_web_service": "Update webservice",
  "web_service": "Web service",
  "dang_xuat": "Logout",
  "cap_nhat_dich_vu": "Update service",
  "danh_sach_job": "List jobs",
  "danh_sach_so_thich": "List hobbies",
  "chon_nhom_dich_vu": "Select service group",
  "chon_dich_vu": "Select service",
  "cap_nhat_khuyen_mai": "Update promotion",
  "web_service": "Web service",
  "noi_dung": "Content",
  "tat_ca": "All",
  "trang_trai_nghiem_3g_4g": "Page 3g/4g exprience",
  "trang_gioi_thieu_ung_dung": "Application page",
  "from_date": "From date",
  "to_date": "To date",
  "hien_thi": "show",
  "hien": "Show",
  "an": "Hide",
  "chon_tinh_thanh_pho": "Select province",
  "chon_quan_huyen": "Select district",
  "lien_ket": "Link",
  "danh_sach_goi_cuoc": "List services",
  "hoat_dong": "Actions",
  "dang_nhap_he_thong": "Login to your account",
  "username": "Username",
  "password": "Password",
  "login": "Login",
  "duong_dan_anh": "Image url",
  "registerable": "Registerable",
  "Un-Registerable": "Un-Registerable",
  "": "",
  "": "",
  "": "",
  //Notification
  "them_moi_notification": 'Add new notification',
  "cap_nhat_notification": 'Edit notification',
  "thong_bao": "Notification",
}

var validateMessages = {
  ErrRequired: 'Field is required',
  ErrMaxLength1: 'Max 1 Characters',
  ErrMaxLength2: 'Max 2 Characters',
  ErrMaxLength20: 'Max 20 Characters',
  ErrMaxLength10: 'Max 10 Characters',
  ErrMaxLength5: 'Max 5 Characters',
  ErrMaxLength6: 'Max 6 Characters',
  ErrMaxLength50: 'Max 50 Characters',
  ErrMaxLength100: 'Max 100 Characters',
  ErrMaxLength200: 'Max 200 Characters',
  ErrMaxLength256: 'Max 256 Characters',
  ErrMaxLength1000: 'Max 1000 Characters',
  ErrMaxLength2000: 'Max 2000 Characters',
  ErrMaxLength4000: 'Max 4000 Characters',
  ErrMaxLength: 'Characters input too long',
  ErrRequiredLanguage: 'Please select language',
  ErrRequiredGroupId: 'Please select service group',
  ErrUrl: 'Invalid url',
  ErrDate: 'Invalid date',
  ErrMin: 'Please input number greater than -999',
  ErrMax: 'Please input number smaller than 999',
  ErrNumber: 'Please input number',
  ErrNotValidInput: 'Invalid input',
  ErrMaxLengthSpecific: 'Max length is',
  ErrRequiredSpecific: 'Required field',
  ErrEffectTimeReq: 'Please input effect date',
  ErrPublicTimeReq: 'Please input publish date',
  ErrExpiredTimeReq: 'Please input expired date',
  ErrPhonePattern: 'Invalid phone number',
  ErrIntNumber: 'Please input integer number',
  ErrMinValue0: 'Please input positive integer number',
  expireDate_larger_effectDate: 'Expire date should be larger than Effect date',
  ErrImageLink: 'Invalid image url',
  ErrMinSpecific: 'Min is',
  ErrMaxSpecific: 'Max is',
  numberFloatMax3: 'Allow to enter float number'
}

var notiMessages = {
  addSuccessMes: "Added successfully",
  putSuccessMes: "Updated successfully",
  errMes: "Error",
  addServiceSuccessMes: "Add Subservice successfully",
  notFound: "Not found",
  loginRequire: "Please re-login",
  ajaxWaiting: "<h2>Waiting...</h2>",
  errEffectiveTimeLagrerThanExpiredTime: "Expired time must be larger than or equal effect time",
  loginFailed: "Username or Password is incorrect",
  duplicate: 'Error! Duplicate data',
  cancelSuccess: 'Cancel successfully',
  cancelFail: 'Cancel fail!'
}

var tableTitles = {
  order: "Order",
  serviceType: "Service",
  promotionType: "Promotion",
  newsType: "News",
  action: "Action",
  deleteMessage: "Do you want to delete?",
  successAddMessage: "Added successfully",
  successDeleteMessage: "Deleted successfully",
  successUpdateMessage: "Updated successfully",
  errorMessage: "Error!",
  errorLoad: "Unable to load",
  edit: "Edit",
  delete: "Delete",
  cancel: "Cancel",
  submit: "Confirm",
  approvedMessage: "Approved",
  unApprovedMessage: "Un-approved",
  approveAll: "Approve all",
  error: "Error",
  total: "Total",
  record: "Rows",
  save: "Save",
  empty: "No record",
  search: "Search",
  infoFilter: "(Filter from",
  zeroRecords: "Not found",
  addNew: "Add",
  refresh: "Refresh",
  //service group
  groupCode: "Group code",
  groupName: "Group name",
  description: "Description",
  language: "Language",
  createdTime: "Created date",
  //service
  serviceCode: "Service code",
  serviceName: "Service name",
  shortDescription: "Short description",
  serviceGroup: "Service group",
  icon: "Icon",
  webLink: "Link",

  //sub service
  subserviceCode: "Subservice code",
  subserviceName: "Subservice name",
  includedInService: "Included in service",

  //actions
  id: "ID",
  actionName: "Action name",
  actionType: "Action type",
  channelType: "Chanel type",
  syntax: "Syntax",
  channel: "Channel",
  webservice: "Webservice",
  register: "Register",

  //Webservice
  name: "Name",
  url: "Url",
  parameter: "Params",
  xmlString: "XML",
  //Promotions
  title: "Title",
  effectiveDate: "Effective Date",
  expiredDate: "Expired date",
  publishingTime: "Published date",
  //news

	service: "Service",
	promotion: "Promotion",
	news: "News",
  sourceLink: "Source link",
  imgDes: "Image description",
  //application
  applicationName: "Application name",
  type: "Type",
  //hotnews
  image: "Image",
  orderOfPrecedence: "order",
  effectiveTime: "Effective time",
  expiredTime: "Expired time",
  display: "Display",
  isShow: "Show",
  notShow: "Hide",
  newsOfType: "New type",
  yes: "Yes",
  no: "No",
  //store
  phoneNumber: "Phone number",
  address: "Address",
  openTime: "Open time",

  //experiment link
  linkName: "Link",


  //banner
  bannerImage: "Banner image",
  messageType: "Message type",
  serviceAd: "Service advertising",
  promotionAd: "Promotion advertising",
  newsAd: "News advertising",
  otherAd: "Other",
  notWorking: "Not working",
  isWorking: "Is working",
  all: "All",
  applicationPage: "Application page",
  experimentPage: "3G/4G experience",
  status: "Status",

  //user
  fullName: "Fullname",
  loginName: "Login name",
  password: "Password",
  role: "Role",
  admin: "Admin",
  contentManager: "Content Manager",

  fromDate: "From date",
  toDate: "To date",

  //other
  jobTitle: "Job title",
  hobbyTitle: "Hobby title",
  longitude: "Longitude",
  latitude: "Latitude",
  province: "Province",
  district: "District",
  //search placeholder
  searchJob: "Search job name",
  searchHobby: "Search hobby name",
  searchShop: "Search shop name",
  searchBanner: "Search banner description",
  searchExprLink: "Seach experience link",
  searchNews: "Search news",
  searchApplication: "Search application",
  searchPromotion: "Search promotion title",
  searchWebservice: "Search webservice",
  searchSubservice: "Search subservice",
  searchService: "Search service",
  searchServiceGroup: "Serch service group",
  searchHotnews: "Search hotnews",
  searchWebservice: "Search webservice name",

  //Notification
  message: 'Message',
  startTime: 'Start time',
  endTime: 'End time',
}
